version: "3.9"

services:
  dcm_master:
    build: .
    container_name: dcm_master_container

    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb

    network_mode: host