CC = clang++
FILES = src/*.cpp
ARGS = 
DEBUG_ARGS = -D DEBUG -g -fno-omit-frame-pointer
RELEASE_ARGS = -Wall -Wextra -s -march=native
LIBS = `pkg-config --cflags --libs opencv4 sdl2` -lSDL2_mixer -lavformat -lavcodec -lavutil -lswscale -lavdevice
EXEC = dcm_master

PREFIX = /usr/local
BINDIR = $(PREFIX)/bin
LIBDIR = $(PREFIX)/lib
INCLUDEDIR = $(PREFIX)/include

debug:
	$(CC) $(ARGS) $(DEBUG_ARGS) $(FILES) $(LIBS) -o $(EXEC)

debug_fps:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_FPS $(FILES) $(LIBS) -o $(EXEC)

debug_ltop:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_TOP -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

debug_0:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D ENABLE_INFO=0 -D ENABLE_MINIMAP=0 -D ENABLE_MINIMAP_FULLSCREEN=1 -D NO_RESIZE=1 $(LIBS) $(FILES) -o $(EXEC)


ignore:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D MAKE_IGNORE $(LIBS) $(FILES) -o $(EXEC)
#
# ==[ BENCHING CPU
#

bench_0:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D ENABLE_MINIMAP_FULLSCREEN=1 $(LIBS) $(FILES) -o $(EXEC)

bench_cpu:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU $(FILES) $(LIBS) -o $(EXEC)

bench_all:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D DISPLAY_MODE=DISPLAY_MODE_ALL -D ENABLE_MOTION=0 $(LIBS) $(FILES) -o $(EXEC)

bench_sort:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D DISPLAY_MODE=DISPLAY_MODE_SORT -D ENABLE_MOTION=0 $(LIBS) $(FILES) -o $(EXEC)

bench_king:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D DISPLAY_MODE=DISPLAY_MODE_KING -D ENABLE_MOTION=0 $(LIBS) $(FILES) -o $(EXEC)

bench_top:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D DISPLAY_MODE=DISPLAY_MODE_TOP -D ENABLE_MOTION=0 $(LIBS) $(FILES) -o $(EXEC)

bench_ltop:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DEBUG_CPU -D DISPLAY_MODE=DISPLAY_MODE_TOP -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

#
# ==[ funky opts
#
tour:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 $(LIBS) $(FILES) -o $(EXEC)

# tour only
to:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D ENABLE_MOTION=0 $(LIBS) $(FILES) -o $(EXEC)

# tour only slow
tos:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D ENABLE_MOTION=0 -D SLEEP_MS_DRAW=100 $(LIBS) $(FILES) -o $(EXEC)

circ:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D ENABLE_MOTION=0 -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_CIRC $(LIBS) $(FILES) -o $(EXEC)

circfast:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D ENABLE_MOTION=0 -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_CIRC -D OVERRIDE_SLEEP=0 $(LIBS) $(FILES) -o $(EXEC)

#
# ==[ layout options
#
single:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_SINGLE $(LIBS) $(FILES) -o $(EXEC)

all:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_ALL $(LIBS) $(FILES) -o $(EXEC)

lall:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_ALL -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

sort:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_SORT $(LIBS) $(FILES) -o $(EXEC)

lsort:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_ALL -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

king:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING $(LIBS) $(FILES) -o $(EXEC)

kingcirc:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=2 $(LIBS) $(FILES) -o $(EXEC)

lking:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

top:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_TOP $(LIBS) $(FILES) -o $(EXEC)

ltop:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_TOP -D ENABLE_MOTION_ZOOM_LARGEST=1 $(LIBS) $(FILES) -o $(EXEC)

ttop:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D DISPLAY_MODE=DISPLAY_MODE_TOP $(LIBS) $(FILES) -o $(EXEC)

totop:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D ENABLE_TOUR=1 -D ENABLE_MOTION=0 -D DISPLAY_MODE=DISPLAY_MODE_TOP $(LIBS) $(FILES) -o $(EXEC)

#
# ==[ install / uninstall
#
music:
	xxd -i sfx/clicky-8-bit-sfx.wav > src/sfx.h


install:
	install -m 755 $(EXEC) $(BINDIR)

uninstall:
	rm -f $(BINDIR)/$(EXEC)

# king, rel, zoom, draw optimized
krzo:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_REL -D ENABLE_MOTION_ZOOM_LARGEST=1 -D SLEEP_MS_FRAME=100 -D SLEEP_MS_DRAW=100 -D SLEEP_MS_MOTION=100 $(LIBS) $(FILES) -o $(EXEC)

krzod:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_REL -D ENABLE_MOTION_ZOOM_LARGEST=1 -D SLEEP_MS_FRAME=100 -D SLEEP_MS_DRAW=100 -D SLEEP_MS_MOTION=100 $(LIBS) $(FILES) -o $(EXEC)

kro:
	$(CC) $(ARGS) $(RELEASE_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_REL -D SLEEP_MS_FRAME=100 -D SLEEP_MS_DRAW=100 -D SLEEP_MS_MOTION=100 $(LIBS) $(FILES) -o $(EXEC)

krod:
	$(CC) $(ARGS) $(DEBUG_ARGS) -D DISPLAY_MODE=DISPLAY_MODE_KING -D KING_LAYOUT=KING_LAYOUT_REL -D SLEEP_MS_FRAME=100 -D SLEEP_MS_DRAW=100 -D SLEEP_MS_MOTION=100 $(LIBS) $(FILES) -o $(EXEC)

release:
	$(CC) $(ARGS) $(RELEASE_ARGS) $(LIBS) $(FILES) -o $(EXEC)
	

